openapi: 3.0.4
info:
  title: Online Subscriptions
  version: 1.0.0

tags:
  - name: Subscriptions
    description: Operations about subscriptions

paths:
  /subscriptions:
    get:
      summary: Получить список всех подписок
      tags:
        - Subscriptions
      operationId: getAllSubscriptions
      responses:
        '200':
          description: Ответ со списком подписок
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'
        '500':
          description: Неудачный запрос на БД / Ошибка сериализации ответа
    post:
      summary: Добавить новую подписку
      tags:
        - Subscriptions
      operationId: createSubscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscription'
      responses:
        '200':
          description: Успешный запрос с возвращением созданного объекта
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '400':
          description: Неправильный requestBody
        '500':
          description: Ошибка вставки в БД / Сериализации ответа
    put:
      summary: Обновить существующую подписку
      tags:
        - Subscriptions
      operationId: updateSubscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscription'
      responses:
        '200':
          description: Успешный запрос с возвращением созданного объекта
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '400':
          description: Неправильный requestBody
        '500':
          description: Ошибка вставки в БД / Сериализации ответа
  
  /subscriptions/{id}:
    get:
      summary: Получить подписку по id
      tags:
        - Subscriptions
      operationId: getSubscriptionById
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор подписки
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: Ответ с подпиской
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '400':
          description: Некорректный тип идентификатора подписки
        '500':
          description: Неудачный запрос на БД / Ошибка сериализации ответа
    delete:
      summary: Получить подписку по id
      tags:
        - Subscriptions
      operationId: deleteSubscriptionById
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор подписки
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: Успешное удаление подписки
        '400':
          description: Некорректный тип идентификатора подписки
        '500':
          description: Неудачный запрос на БД / Ошибка сериализации ответа
    
  /subscriptions/sum:
    get:
      summary: Получить суммарную стоимость всех подписок за выбранный период с фильтрацией по id пользователя и названию подписки
      tags:
        - Subscriptions
      operationId: getSummaryPriceOfSubscriptions
      parameters:
        - name: startDate
          in: query
          required: true
          description: Начало периода
          schema:
            type: string
          example: 07 2025
          
        - name: endDate
          in: query
          required: true
          description: Конец периода
          schema:
            type: string
          example: 10 2025
        
        - name: userId
          in: query
          required: true
          description: Идентификатор пользователя, чьи подписки учитываются в стоимости
          schema:
            type: string
          example: 86272c89-780c-4efe-9cde-d13754bc5f96
          
        - name: serviceName
          in: query
          required: true
          description: Название сервиса, который учитывается при подсчете стоимости для пользователя в указанный период
          schema:
            type: string
          example: Yandex Plus
          
      responses:
        '200':
          description: Ответ с подпиской
          content:
            text/plain:
              schema:
                type: string
                example: 1050
        '400':
          description: Неправильный формат начала и/или конца периода
        '405':
          description: Неправильный метод
        '500':
          description: Ошибка при запросе в БД
    
components:
  schemas:
    Subscription:
      type: object
      properties:
        id:
          type: integer
          example: 1
        service_name:
          type: string
          example: Yandex Plus
        price:
          type: integer
          example: 390
        user_id:
          type: string
          example: 86272c89-780c-4efe-9cde-d13754bc5f96
        start_date:
          type: string
          example: "07-2025"
        end_date:
          type: string
          example: "10-2025"
        deleted:
          type: boolean
          example: false